from .benefits import BenefitsAdmin
from .brands_list_page import BrandListPageAdmin
from .brands_page import BasePageAdmin
from .catalog_page import CatalogPageAdmin
from .category_page import CategoryPageAdmin
from .contact_page import ContactPageAdmin
from .home_page import HomePageAdmin
from .news_list_page import NewsListPageAdmin
from .news_page import NewsPageAdmin
from .product_page import ProductPageAdmin
from .promo_slider import PromoSliderAdmin
from .site_configuration import SingletonModelAdmin
