from .benefits import Benefits
from .brand_list_page import BrandListPage
from .brand_page import BrandPage
from .catalog_page import CatalogPage
from .category_page import ProductsCategoryPage
from .contact_page import ContactPage
from .home_page import HomePage
from .news_list_page import NewsListPage
from .news_page import NewsPage
from .product_page import ProductPage
from .promo_slider import PromoSlider
