# Generated by Django 3.1 on 2021-08-01 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0001_initial'),
        ('electroplace', '0002_catalogpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
                ('city', models.CharField(blank=True, default='', max_length=250, verbose_name='Город')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='E-mail')),
                ('tabletime', models.CharField(blank=True, default='', max_length=100, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.RemoveField(
            model_name='catalogpage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='catalogpage',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='catalogpage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='catalogpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='catalogpage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='catalogpage',
            name='tabletime',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='tabletime',
        ),
    ]
