# Generated by Django 3.1 on 2021-08-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("garpix_page", "0001_initial"), ("electroplace", "0003_auto_20210802_0002")]

    operations = [
        migrations.CreateModel(
            name="BrandsPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garpix_page.basepage",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True, verbose_name="Название")),
                ("desc_brands", models.TextField(blank=True, verbose_name="Описание")),
                ("image", models.ImageField(blank=True, upload_to="Изображение")),
            ],
            options={"verbose_name": "Бренд", "verbose_name_plural": "Бранды"},
            bases=("garpix_page.basepage",),
        ),
        migrations.CreateModel(
            name="ProductsCategory",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garpix_page.basepage",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True, verbose_name="Категория")),
                ("desc_category", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
            bases=("garpix_page.basepage",),
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garpix_page.basepage",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Продукт")),
                ("image", models.ImageField(blank=True, upload_to="Изображение")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Цена")),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8, verbose_name="Старая цена"
                    ),
                ),
                (
                    "screen",
                    models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name="Экран"),
                ),
                ("sim", models.PositiveIntegerField(blank=True, default=0, verbose_name="Кол-во сим карт")),
                ("storage", models.PositiveIntegerField(blank=True, default=0, verbose_name="Хранилище")),
                ("color", models.CharField(blank=True, max_length=128, verbose_name="Цвет")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="Кол-во")),
                ("is_stock", models.BooleanField(db_index=True, default=False, verbose_name="В акции")),
                ("is_new", models.BooleanField(db_index=True, default=False, verbose_name="Новинка")),
                (
                    "brands",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="electroplace.brandspage"),
                ),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="electroplace.productscategory"),
                ),
            ],
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары", "ordering": ("-created_at",)},
            bases=("garpix_page.basepage",),
        ),
    ]
